### ISSUE TITLE
Size can be string

### ISSUE THREAD

**Issue by cagataysayg** [Farzin-Firoozi/react-modern-drawer#10]
Size type declared as number but it can be string too. For example, it can be one of those px, vh, vw etc.

![image](https://user-images.githubusercontent.com/32942141/160175373-14936ec7-2d64-4731-a6b8-662259e8fb32.png)

**Comment by Farzin-Firoozi** [comment]
If you want to do that you can pass width to the `style` prop and it overwrites the size.
```jsx
<Drawer style={{ width: '50vw' }} >
...
```
take a look at [this](https://github.com/Farzin-Firoozi/react-modern-drawer/blob/master/src/index.tsx#L88).

**Comment by cagataysayg** [comment]
That's how I already did it but I just wanted to improve the code.

**Comment by Farzin-Firoozi** [comment]
Can you make a PR for it?

**Comment by cagataysayg** [comment]
> 

Need access to create a branch

**Comment by Farzin-Firoozi** [comment]
This feature is available now in v1.0.3! 🥳
