### ISSUE TITLE
SSR Issue: Prop id did not match

### ISSUE THREAD

**Issue by martinmckenna** [Farzin-Firoozi/react-modern-drawer#13]
I'm currently using this drawer component in my SSR remix app. Since this component is being rendered both on the server and on the client, I end up with the component having two different `id` props:

<img width="479" alt="Screen Shot 2022-07-18 at 12 50 21 PM" src="https://user-images.githubusercontent.com/7387001/179605481-020d877b-9ff5-4f40-a522-14a50a3f19d6.png">

Could you please add the ability to pass `idSuffix` as a prop, so the `Math.random()` doesn't get run twice for server and client and they will match.

Here's a similar issue from react-select: https://github.com/JedWatson/react-select/issues/2629

**Comment by Farzin-Firoozi** [comment]
Thanks for your notice.
This fixes this issue 👉🏻 #14 .

**Comment by martinmckenna** [comment]
perfect! thanks so much!
