### ISSUE TITLE
Responsive Sizing?

### ISSUE THREAD

**Issue by TjBruhn** [Farzin-Firoozi/react-modern-drawer#31]
Does the drawer support responsive sizing? I want a drawer that is 50vw and then 100vw at a breakpoint, is that possible?
I am finding that if I pass a size value (in any of the allowed formats) the drawer does not adapt to window width. However if I pass an empty string the drawer becomes responsive but at some preset width on larger screens and full width on small screens.

**Comment by Farzin-Firoozi** [comment]
You can achieve this by using `className`, creating media queries, and changing its `width`.

**Comment by TjBruhn** [comment]
Thanks, I will try that. 
It would be a cool additional feature if you could set the responsive sizing inline. Or even if there was just an optional property that allowed you to define the window width at which it should switch to full width.

**Comment by sroze** [comment]
For those using MUI and interested in how to reuse the media query breakpoints, here's our `ResponsiveDrawer`:

```tsx
export const ResponsiveDrawer = (props: ComponentProps<typeof Drawer>) => {
  const theme = useTheme();
  const isLargeEnough = useMediaQuery(theme.breakpoints.up("md"));

  return <Drawer {...props} size={isLargeEnough ? "65%" : "100%"} />;
};
```
