### ISSUE TITLE
Adding Close Button (optional) and Full screen Drawer

### ISSUE THREAD

**Issue by carlospence** [Farzin-Firoozi/react-modern-drawer#35]
Hi,

Having an in-built close at the top left or right corner of the drawer will be a great feature. Showing the close button can be optional and controlled by a prop. 

Also, how can a fullscreen be achieved and must be very presentable on mobile? The in-built close button should be automatically on when on fullscreen.

**Comment by Farzin-Firoozi** [comment]
Hi,I've tried to keep things as simple as possible with complete flexibility in this package.
For having a fullscreen drawer you can set the width to `100vw`, for the close button, you can implement it the way you prefer.
