### ISSUE TITLE
Prop Mismatch on Client vs Server [NextJS]

### ISSUE THREAD

**Issue by boncz92** [Farzin-Firoozi/react-modern-drawer#37]
Issue is presenting itself when using nextjs which by default uses Server Components. I tried wrapping the component in a wrapper using the 'use client' directive but still seeing the issue. Curious if any one else has run into this and has some insight into how to fix it.

**Comment by boncz92** [comment]
Warning: Prop `id` did not match. Server: "EZDrawer__checkbox0v6vrl" Client: "EZDrawer__checkboxna3je"

**Comment by AguacateVelarde** [comment]
Hey there! You might consider using dynamic import. Here's the component


```jsx
const Drawer = dynamic(() => import('react-modern-drawer'), {
  suspense: true,
});

const MyComponent = () => (
  <Drawer>...</Drawer>
);
```

**Comment by greengem** [comment]
> Hey there! You might consider using dynamic import. Here's the component
> 
> ```js
> const Drawer = dynamic(() => import('react-modern-drawer'), {
>   suspense: true,
> });
> 
> const MyComponent = () => (
>   <Drawer>...</Drawer>
> );
> ```

This indeed fixes the error but now the drawer has no animation, when opening it appears immediately.

**Comment by baktun14** [comment]
I get the same error as well.

**Comment by epignosisx** [comment]
Use the `customIdSuffix` prop.

**Comment by boncz92** [comment]
> Use the `customIdSuffix` prop. It solved my problem because now it will use this id in the server and client instead of generating a different one on each side.

Man am I dumb, I literally did just this but instead a took the source code changed it in the source and was using that I just had to read through it a bit more and woulda saw this. I appreciate the information man. Will close this issue in the morning when I validate.

**Comment by boncz92** [comment]
> Use the `customIdSuffix` prop. It solved my problem because now it will use this id in the server and client instead of generating a different one on each side.

Right on the money. Thanks man.
