### ISSUE TITLE
Support React 17.0.2

### ISSUE THREAD

**Issue by EvgeniiZaikin** [Farzin-Firoozi/react-modern-drawer#4]
Try npm I react-modern-drawer:

code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: click2js@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.0.0" from react-modern-drawer@1.0.1
npm ERR! node_modules/react-modern-drawer
npm ERR!   react-modern-drawer@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by Farzin-Firoozi** [comment]
Can you give more information on this? as I couldn't reproduce it.
I created a project with the latest version of react which is 17.0.2 and had no issue.
