### ISSUE TITLE
lockBackgroundScroll can be improved

### ISSUE THREAD

**Issue by smnbbrv** [Farzin-Firoozi/react-modern-drawer#44]
First of all, thank you for a great library!

The current implementation (https://github.com/Farzin-Firoozi/react-modern-drawer/blob/0bf3ee8d4f06ae631d25707ba4d5d3f725ff3ac2/src/index.tsx#L92C1-L93C1) of `lockBackgroundScroll` is kinda weak and there are many various scenarios when it won't work as expected. E.g. another JS function that manipulates the body's overflow property (or simply wipes out the style property), typically another modal library, or a nested drawer can remove it, etc

A bit better approach could be generating a class for each drawer instance and put it on body. That's what I do to deal with this issue right now in my wrapper around this drawer:

```tsx
import { FunctionComponent, useEffect, useRef } from 'react';
import ReactModernDrawer from 'react-modern-drawer';
import 'react-modern-drawer/dist/index.css';

export type DrawerProps = {
  open?: boolean;
  onClose?: () => void;
  children?: React.ReactNode;
  size?: string;
};

let drawerCount = 0;

export const Drawer: FunctionComponent<DrawerProps> = ({
  open = false,
  onClose = () => null,
  children,
  size = '70vw',
}) => {
  const bodyClassNameRef = useRef(`react-modern-drawer-open-${drawerCount++}`);

  useEffect(() => {
    const bodyClassName = bodyClassNameRef.current;
    const { classList } = document.body;

    if (open) {
      classList.add(bodyClassName);
    } else {
      classList.remove(bodyClassName);
    }

    return () => {
      classList.remove(bodyClassName);
    };
  }, [open]);

  return (
    <ReactModernDrawer
      open={open}
      onClose={() => {
        onClose();
      }}
      direction="right"
      duration={150}
      size={size}
      // lockBackgroundScroll
    >
      {children}
    </ReactModernDrawer>
  );
};
```

and global CSS:

```css
body[class*="react-modern-drawer-open-"] {
  overflow: hidden !important;
}
```

This of course does not solve all potential breaking mechanics, however it is waaay harder to break it now

**Comment by Farzin-Firoozi** [comment]
Thanks for your recommendation,
Can you create a PR for this?

**Comment by smnbbrv** [comment]
I've ended up using the shadcn sheet component, it was a better fit to me. Thanks for a starting point anyway!

You can close the issue if this won't be relevant
