### ISSUE TITLE
onClose function issue

### ISSUE THREAD

**Issue by thib3113** [Farzin-Firoozi/react-modern-drawer#8]
Hello, like #3 I have a problem with the onClose . 

And I think I know why . 

you are using, non uniq ids for the drawers . So, if I use two drawers, one open, and one closed, I have two elements with Id `EZDrawer__overlay` .
![image](https://user-images.githubusercontent.com/5489218/159806529-469df9bb-3c4d-4f2f-9e26-8dce91fcee0e.png)

And because you are using label for checkbox . I think when you click on `#EZDrawer__overlay` from Drawer2, it will check one of the two `#EZDrawer__checkbox`, and not always the correct one . In my case, Drawer1 is before in the HTML tree, so (I think) clicking on Drawer2 overlay, call the Drawer1 onclose function . 

A solution can be to append ids from `useId` on your elements . And use a className for CSS .

---

After some search, `useId` will be available in React 18 not before ... so a Date.now() can be enough to get uniq id .

**Comment by Farzin-Firoozi** [comment]
I think this [solution](https://github.com/Farzin-Firoozi/react-modern-drawer/issues/3#issuecomment-1036053839) can help you with multiple drawers.

**Comment by thib3113** [comment]
@Farzin-Firoozi the problem is not the z-index .... the problem is, when you click on the overlay, you click on the label for the id of the checkbox ... And if you have multiple inputs with this ID, in the document, the browser will choose to click on one of them ... not depending of the zindex ...
